// app/layout.tsx

import { Inter } from "next/font/google";
import "./globals.css";
import type React from "react";
import { cn } from "@/lib/utils";
import { fontSans } from "@/lib/fonts";
import SpaceBackground from "@/app/components/SpaceBackground";
import ClientWrapper from "@/components/ClientWrapper";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-gradient-to-b from-black to-gray-900 font-sans antialiased"
,
          fontSans.variable
        )}
      >
        <div className="relative min-h-screen overflow-hidden">
          <SpaceBackground />
          <div className="relative z-10">
            <ThemeProvider>
              <ClientWrapper>{children}</ClientWrapper>
            </ThemeProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
